# Generated by Django 5.2.11 on 2026-02-27 06:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('HELP', 'Help Required'), ('DOCTOR', 'Doctor Needed'), ('EMERGENCY', 'Emergency'), ('DANGER', 'Danger'), ('POLICE', 'Police'), ('FIRE', 'Fire'), ('AMBULANCE', 'Ambulance'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('message', models.TextField()),
                ('confidence', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='ACTIVE', max_length=20)),
                ('whatsapp_sent', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Emergency Alert',
                'verbose_name_plural': 'Emergency Alerts',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TranslationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('word', models.CharField(max_length=200)),
                ('confidence', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_emergency', models.BooleanField(default=False)),
                ('audio_generated', models.BooleanField(default=False)),
                ('whatsapp_sent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Translation History',
                'verbose_name_plural': 'Translation Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_translations', models.IntegerField(default=0)),
                ('emergency_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(help_text='Include country code e.g. +919876543210', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_emergency_contact', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_messaged', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Contact',
                'verbose_name_plural': 'WhatsApp Contacts',
                'ordering': ['name'],
            },
        ),
    ]
